// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilavaqzlwppxuczgvdsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsYXZhcXpsd3BweHVjemd2ZHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2OTI4MjAsImV4cCI6MjA2NDI2ODgyMH0.7cKmDsAzxA2bv9Q8VAq4XTg7BOq-_9h5l997Pac2gOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);